/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
num particles: 1
train dataset size: 50000
test dataset size: 10000
  0%|                                                                        | 0/1563 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/revanth/DMAT-Variants/prepare_classifiers_adv_dual_mix10_ours.py", line 582, in <module>
    train_overall_loss = train(epoch)
  File "/home/revanth/DMAT-Variants/prepare_classifiers_adv_dual_mix10_ours.py", line 450, in train
    latents_adv = latent_attacker.perturb(latents, labels)
  File "/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/advertorch/attacks/iterative_projected_gradient.py", line 183, in perturb
    rval = perturb_iterative(
  File "/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/advertorch/attacks/iterative_projected_gradient.py", line 65, in perturb_iterative
    outputs = predict(xvar + delta)
  File "/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 183, in forward
    return self.module(*inputs[0], **module_kwargs[0])
  File "/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/revanth/DMAT-Variants/stylegan_old/stylegan_generator_model.py", line 384, in forward
    x = self.__getattr__(f'layer{layer_idx}')(x, w[:, layer_idx])
IndexError: index 8 is out of bounds for dimension 1 with size 8
Latents:  torch.Size([32, 8, 512]) torch.Size([32])
lod: 0.0
w tensor shape: torch.Size([32, 8, 512])
Attempting to access layer index: 0
w tensor shape: torch.Size([32, 8, 512])
Attempting to access layer index: 2
w tensor shape: torch.Size([32, 8, 512])
Attempting to access layer index: 4
w tensor shape: torch.Size([32, 8, 512])
Attempting to access layer index: 6
w tensor shape: torch.Size([32, 8, 512])
Attempting to access layer index: 8